name: httpserver-contianr-image

on:
  push:
    branches: [ "deployment" ]
    
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  
jobs:
  bump-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask:$(date +%s)
    - name: Upload to docker hub
      run: docker push ${{ dockerhubusername }}:${{ tags }}
